# Tell Travis CI we're using PHP
language: php

# Using trusty instead of precise because we don't need PHP 5.2 or 5.3 anymore.
dist: trusty

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.jest-cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin

branches:
  only:
    - develop
    - /^\d+\.\d+$/

install:
  - nvm install
  - composer install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - export DIFF_HEAD=HEAD
  - source "$DEV_LIB_PATH/travis.install.sh"

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist."

script:
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:
  fast_finish: true
  include:
    - stage: lint
      name: Lint (PHP, JavaScript, and configuration files)
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpsyntax
      before_script:
        - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist."
      script:
        - source "$DEV_LIB_PATH/travis.script.sh"

    - stage: test
      name: PHP unit tests (7.2, WordPress latest)
      php: "7.2"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit,phpsyntax

    - name: PHP unit tests (7.1, WordPress latest)
      php: "7.1"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit,phpsyntax

    - name: PHP unit tests (7.0, WordPress 5.2)
      php: "7.0"
      env: WP_VERSION=5.2 DEV_LIB_ONLY=phpunit,phpsyntax

    - name: PHP unit tests (7.3, WordPress trunk)
      php: "7.3"
      env: WP_VERSION=trunk  DEV_LIB_ONLY=phpunit
